server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail_search?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  elasticsearch:
    uris: http://localhost:9200

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      # password: redis_password
  cache:
    type: redis
    redis:
      time-to-live: 600000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id

mail:
  store:
    protocol: imap
  imap:
    host: imap.your-mail-provider.com
    port: 993
    ssl:
      enable: true
  user: your-email@example.com
  password: your-app-specific-password